#!/bin/bash

if [ $# -ne "1" ]; then
    echo "/!\ Veuillez entrer l'identifiant du mot à traduire"
    exit 1
fi

read -p 'Entrez la traduction Francaise : ' francais
read -p 'Entrez la traduction Anglaise : ' anglais

txtfinalfr="\"$1\":\"$francais\",\n\t\"insert\" : \"insert\""
txtfinalen="\"$1\":\"$anglais\",\n\t\"insert\" : \"insert\""

chemin="./lib/PRESENTATION/core/_l10n/app_fr.arb"
sed -i -e "s~\"insert\" : \"insert\"~$txtfinalfr~g" "$chemin"

chemin="./lib/PRESENTATION/core/_l10n/app_en.arb"
sed -i -e "s~\"insert\" : \"insert\"~$txtfinalen~g" "$chemin"

rm -f ./lib/PRESENTATION/core/_l10n/*.arb-e